// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-upcoming-appointments.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_upcoming_appointments_default = defineTool({
  name: "list_upcoming_appointments",
  title: "List upcoming appointments",
  description: "List upcoming/scheduled appointments visible to the signed-in clinician.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const { data, error } = await supabaseForUser(ctx).from("appointments").select(
      "id, full_name, mobile_number, status, assigned_program, assigned_to, created_at, notes"
    ).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-consultations.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_recent_consultations_default = defineTool2({
  name: "list_recent_consultations",
  title: "List recent consultations",
  description: "List the signed-in clinician's most recent consultations, optionally filtered by program.",
  inputSchema: {
    program: z2.enum(["peptides", "weight-loss"]).optional().describe("Filter by program."),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ program, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    let query = supabaseForUser2(ctx).from("consultations").select(
      "id, patient_name, program, status, created_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (program) query = query.eq("program", program);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-consultation.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_consultation_default = defineTool3({
  name: "get_consultation",
  title: "Get consultation",
  description: "Fetch a single consultation (intake, AI recommendations, doctor notes, guidelines, next steps) by id.",
  inputSchema: {
    id: z3.string().uuid().describe("Consultation id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const { data, error } = await supabaseForUser3(ctx).from("consultations").select("*").eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "Consultation not found" }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { consultation: data }
    };
  }
});

// src/lib/mcp/tools/search-clinical-documents.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_clinical_documents_default = defineTool4({
  name: "search_clinical_documents",
  title: "Search clinical knowledge base",
  description: "Search the clinic's knowledge base (protocols, patient guides, references) by keyword in title or content.",
  inputSchema: {
    query: z4.string().min(1).describe("Keyword to search for."),
    document_type: z4.string().optional().describe("Optional document_type filter (e.g. 'protocol', 'guide')."),
    limit: z4.number().int().min(1).max(25).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, document_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const like = `%${query.replace(/[%_]/g, (m) => `\\${m}`)}%`;
    let q = supabaseForUser4(ctx).from("clinical_documents").select("id, title, document_type, peptide_name, created_at").or(`title.ilike.${like},content.ilike.${like}`).order("created_at", { ascending: false }).limit(limit ?? 15);
    if (document_type) q = q.eq("document_type", document_type);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kokottennducgqcearxu";
var mcp_default = defineMcp({
  name: "peptidoc-mcp",
  title: "PeptiDOC MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the PeptiDOC clinical consultation platform. Use `list_upcoming_appointments` and `list_recent_consultations` to browse a clinician's workload, `get_consultation` to inspect a full record (intake, AI recommendations, doctor notes), and `search_clinical_documents` to look up peptide protocols and patient guides.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_upcoming_appointments_default,
    list_recent_consultations_default,
    get_consultation_default,
    search_clinical_documents_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
